# ----------- CONFIGURABLE START -----------
title:            "momoxiaoming的博客"
description:      "Full Stack独立开发者|欢迎来到 momoxiaoming「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              https://momoxiaoming.github.io # 域名
signoff:          "momoxiaoming" # Your name
facebook_appid:   #momoxiaoming
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "momoxiaomingpage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         iOS
    url:          /book
    external:     false
  - name:         Android
    url:          /road
    external:     false
  - name:         Python
    url:          /archives
    external:     false
  - name:         Cocos2d-Js
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
